sonar.projectName=tech-challenge-project

sonar.sources=cmd,internal,pkg
sonar.tests=internal/tests

sonar.exclusions=**/*_test.go,internal/tests/**,docs/**,bin/**,tmp/**,vendor/**,.github/**,**/migrations/**,**/*.sql
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=**/*_test.go,docs/**,bin/**,tmp/**,vendor/**,.github/**,**/migrations/**,**/*.sql,**/mock*/**,**/*mock*.go,**/*_mock.go,**/*generated*.go,**/*_gen.go
