apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: docker.io/gustavodetoni/tech-challenge-project
    newTag: 1.1.3
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: tech-challenge-api-secret
    namespace: tech-challenge
    envs:
      - .env.k8s.local
  - name: tech-challenge-postgres-secret
    namespace: tech-challenge
    envs:
      - .env.k8s.local
