// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/soat-architecture/tech-challenge-project/internal/domain/client"
)

type ClientRepository struct {
	mock.Mock
}

func (m *ClientRepository) Create(ctx context.Context, c *client.Client) error {
	args := m.Called(ctx, c)
	return args.Error(0)
}

func (m *ClientRepository) Update(ctx context.Context, c *client.Client) error {
	args := m.Called(ctx, c)
	return args.Error(0)
}

func (m *ClientRepository) Delete(ctx context.Context, id string) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *ClientRepository) FindByID(ctx context.Context, id string) (*client.Client, error) {
	args := m.Called(ctx, id)
	var out *client.Client
	if v := args.Get(0); v != nil {
		out = v.(*client.Client)
	}
	return out, args.Error(1)
}

func (m *ClientRepository) FindByDocument(ctx context.Context, documentNumber string) (*client.Client, error) {
	args := m.Called(ctx, documentNumber)
	var out *client.Client
	if v := args.Get(0); v != nil {
		out = v.(*client.Client)
	}
	return out, args.Error(1)
}

func (m *ClientRepository) List(ctx context.Context, limit, offset int) ([]client.Client, error) {
	args := m.Called(ctx, limit, offset)
	var out []client.Client
	if v := args.Get(0); v != nil {
		out = v.([]client.Client)
	}
	return out, args.Error(1)
}
