// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/soat-architecture/tech-challenge-project/internal/domain/part"
)

type PartRepository struct {
	mock.Mock
}

func (m *PartRepository) Create(ctx context.Context, p *part.Part) error {
	args := m.Called(ctx, p)
	return args.Error(0)
}

func (m *PartRepository) Update(ctx context.Context, p *part.Part) error {
	args := m.Called(ctx, p)
	return args.Error(0)
}

func (m *PartRepository) Delete(ctx context.Context, id string) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *PartRepository) FindByID(ctx context.Context, id string) (*part.Part, error) {
	args := m.Called(ctx, id)
	var out *part.Part
	if v := args.Get(0); v != nil {
		out = v.(*part.Part)
	}
	return out, args.Error(1)
}

func (m *PartRepository) FindByIDs(ctx context.Context, ids []string) ([]part.Part, error) {
	args := m.Called(ctx, ids)
	var out []part.Part
	if v := args.Get(0); v != nil {
		out = v.([]part.Part)
	}
	return out, args.Error(1)
}

func (m *PartRepository) List(ctx context.Context, limit, offset int) ([]part.Part, error) {
	args := m.Called(ctx, limit, offset)
	var out []part.Part
	if v := args.Get(0); v != nil {
		out = v.([]part.Part)
	}
	return out, args.Error(1)
}

func (m *PartRepository) AdjustStock(ctx context.Context, partID string, movementType part.StockMovementType, quantity int, notes *string, createdByUserID *string) (*part.Part, error) {
	args := m.Called(ctx, partID, movementType, quantity, notes, createdByUserID)
	var out *part.Part
	if v := args.Get(0); v != nil {
		out = v.(*part.Part)
	}
	return out, args.Error(1)
}
