// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/soat-architecture/tech-challenge-project/internal/domain/service"
)

type ServiceRepository struct {
	mock.Mock
}

func (m *ServiceRepository) Create(ctx context.Context, s *service.Service) error {
	args := m.Called(ctx, s)
	return args.Error(0)
}

func (m *ServiceRepository) Update(ctx context.Context, s *service.Service) error {
	args := m.Called(ctx, s)
	return args.Error(0)
}

func (m *ServiceRepository) Delete(ctx context.Context, id string) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *ServiceRepository) FindByID(ctx context.Context, id string) (*service.Service, error) {
	args := m.Called(ctx, id)
	var out *service.Service
	if v := args.Get(0); v != nil {
		out = v.(*service.Service)
	}
	return out, args.Error(1)
}

func (m *ServiceRepository) FindByIDs(ctx context.Context, ids []string) ([]service.Service, error) {
	args := m.Called(ctx, ids)
	var out []service.Service
	if v := args.Get(0); v != nil {
		out = v.([]service.Service)
	}
	return out, args.Error(1)
}

func (m *ServiceRepository) List(ctx context.Context, limit, offset int) ([]service.Service, error) {
	args := m.Called(ctx, limit, offset)
	var out []service.Service
	if v := args.Get(0); v != nil {
		out = v.([]service.Service)
	}
	return out, args.Error(1)
}
