// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	"context"
	"time"

	"github.com/stretchr/testify/mock"

	"github.com/soat-architecture/tech-challenge-project/internal/domain/order"
	"github.com/soat-architecture/tech-challenge-project/internal/interfaces/repository"
)

type ServiceOrderRepository struct {
	mock.Mock
}

func (m *ServiceOrderRepository) List(ctx context.Context, limit, offset int, status *order.Status) ([]order.ServiceOrderSummary, error) {
	args := m.Called(ctx, limit, offset, status)
	var out []order.ServiceOrderSummary
	if v := args.Get(0); v != nil {
		out = v.([]order.ServiceOrderSummary)
	}
	return out, args.Error(1)
}

func (m *ServiceOrderRepository) FindByID(ctx context.Context, id string) (*order.ServiceOrder, error) {
	args := m.Called(ctx, id)
	var out *order.ServiceOrder
	if v := args.Get(0); v != nil {
		out = v.(*order.ServiceOrder)
	}
	return out, args.Error(1)
}

func (m *ServiceOrderRepository) GetDetailByID(ctx context.Context, id string) (*order.ServiceOrderDetail, error) {
	args := m.Called(ctx, id)
	var out *order.ServiceOrderDetail
	if v := args.Get(0); v != nil {
		out = v.(*order.ServiceOrderDetail)
	}
	return out, args.Error(1)
}

func (m *ServiceOrderRepository) AverageExecutionMinutes(ctx context.Context, from, to *time.Time) (float64, error) {
	args := m.Called(ctx, from, to)
	var out float64
	if v := args.Get(0); v != nil {
		out = v.(float64)
	}
	return out, args.Error(1)
}

func (m *ServiceOrderRepository) AverageServiceExecutionMinutes(ctx context.Context, serviceID *string, from, to *time.Time) ([]repository.ServiceExecutionAverage, error) {
	args := m.Called(ctx, serviceID, from, to)
	var out []repository.ServiceExecutionAverage
	if v := args.Get(0); v != nil {
		out = v.([]repository.ServiceExecutionAverage)
	}
	return out, args.Error(1)
}
