// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	repository "github.com/soat-architecture/tech-challenge-project/internal/application/port"
	"github.com/soat-architecture/tech-challenge-project/internal/domain/order"
)

type ServiceOrderFlowRepository struct {
	mock.Mock
}

func (m *ServiceOrderFlowRepository) CreateDraft(ctx context.Context, p repository.CreateServiceOrderDraftParams) (*order.ServiceOrder, *order.Budget, error) {
	args := m.Called(ctx, p)
	var so *order.ServiceOrder
	if v := args.Get(0); v != nil {
		so = v.(*order.ServiceOrder)
	}
	var b *order.Budget
	if v := args.Get(1); v != nil {
		b = v.(*order.Budget)
	}
	return so, b, args.Error(2)
}

func (m *ServiceOrderFlowRepository) CreateBudgetRevision(ctx context.Context, p repository.CreateBudgetRevisionParams) (*order.Budget, error) {
	args := m.Called(ctx, p)
	var b *order.Budget
	if v := args.Get(0); v != nil {
		b = v.(*order.Budget)
	}
	return b, args.Error(1)
}

func (m *ServiceOrderFlowRepository) StartDiagnosis(ctx context.Context, serviceOrderID string, changedByUserID *string) error {
	args := m.Called(ctx, serviceOrderID, changedByUserID)
	return args.Error(0)
}

func (m *ServiceOrderFlowRepository) SendLatestBudget(ctx context.Context, serviceOrderID string, changedByUserID *string) error {
	args := m.Called(ctx, serviceOrderID, changedByUserID)
	return args.Error(0)
}

func (m *ServiceOrderFlowRepository) Finish(ctx context.Context, serviceOrderID string, changedByUserID *string) error {
	args := m.Called(ctx, serviceOrderID, changedByUserID)
	return args.Error(0)
}

func (m *ServiceOrderFlowRepository) Deliver(ctx context.Context, serviceOrderID string, changedByUserID *string) error {
	args := m.Called(ctx, serviceOrderID, changedByUserID)
	return args.Error(0)
}

func (m *ServiceOrderFlowRepository) GetNotificationDataByID(ctx context.Context, serviceOrderID string) (*repository.ServiceOrderNotificationData, error) {
	args := m.Called(ctx, serviceOrderID)
	var out *repository.ServiceOrderNotificationData
	if v := args.Get(0); v != nil {
		out = v.(*repository.ServiceOrderNotificationData)
	}
	return out, args.Error(1)
}

func (m *ServiceOrderFlowRepository) GetClientViewByCode(ctx context.Context, code string, documentNumber string) (*repository.ClientServiceOrderView, error) {
	args := m.Called(ctx, code, documentNumber)
	var out *repository.ClientServiceOrderView
	if v := args.Get(0); v != nil {
		out = v.(*repository.ClientServiceOrderView)
	}
	return out, args.Error(1)
}

func (m *ServiceOrderFlowRepository) ApproveLatestBudgetByCode(ctx context.Context, code string, documentNumber string, approvedByName *string) error {
	args := m.Called(ctx, code, documentNumber, approvedByName)
	return args.Error(0)
}

func (m *ServiceOrderFlowRepository) RejectLatestBudgetByCode(ctx context.Context, code string, documentNumber string, rejectionReason string) error {
	args := m.Called(ctx, code, documentNumber, rejectionReason)
	return args.Error(0)
}
