// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/soat-architecture/tech-challenge-project/internal/domain/user"
)

type UserRepository struct {
	mock.Mock
}

func (m *UserRepository) Create(ctx context.Context, u *user.User) error {
	args := m.Called(ctx, u)
	return args.Error(0)
}

func (m *UserRepository) FindByEmail(ctx context.Context, email string) (*user.User, error) {
	args := m.Called(ctx, email)
	var out *user.User
	if v := args.Get(0); v != nil {
		out = v.(*user.User)
	}
	return out, args.Error(1)
}

func (m *UserRepository) FindByID(ctx context.Context, id string) (*user.User, error) {
	args := m.Called(ctx, id)
	var out *user.User
	if v := args.Get(0); v != nil {
		out = v.(*user.User)
	}
	return out, args.Error(1)
}

func (m *UserRepository) UpdateRole(ctx context.Context, id string, role user.Role) error {
	args := m.Called(ctx, id, role)
	return args.Error(0)
}
