// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/soat-architecture/tech-challenge-project/internal/domain/vehicle"
)

type VehicleRepository struct {
	mock.Mock
}

func (m *VehicleRepository) Create(ctx context.Context, v *vehicle.Vehicle) error {
	args := m.Called(ctx, v)
	return args.Error(0)
}

func (m *VehicleRepository) Update(ctx context.Context, v *vehicle.Vehicle) error {
	args := m.Called(ctx, v)
	return args.Error(0)
}

func (m *VehicleRepository) Delete(ctx context.Context, id string) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *VehicleRepository) FindByID(ctx context.Context, id string) (*vehicle.Vehicle, error) {
	args := m.Called(ctx, id)
	var out *vehicle.Vehicle
	if v := args.Get(0); v != nil {
		out = v.(*vehicle.Vehicle)
	}
	return out, args.Error(1)
}

func (m *VehicleRepository) FindByPlate(ctx context.Context, plate string) (*vehicle.Vehicle, error) {
	args := m.Called(ctx, plate)
	var out *vehicle.Vehicle
	if v := args.Get(0); v != nil {
		out = v.(*vehicle.Vehicle)
	}
	return out, args.Error(1)
}

func (m *VehicleRepository) ListByClientID(ctx context.Context, clientID string, limit, offset int) ([]vehicle.Vehicle, error) {
	args := m.Called(ctx, clientID, limit, offset)
	var out []vehicle.Vehicle
	if v := args.Get(0); v != nil {
		out = v.([]vehicle.Vehicle)
	}
	return out, args.Error(1)
}
