apiVersion: v1
kind: ServiceAccount
metadata:
  name: tech-challenge-api
  namespace: tech-challenge
  labels:
    app.kubernetes.io/name: tech-challenge-api
    app.kubernetes.io/component: api
automountServiceAccountToken: false
