name: Sonar

on:
  workflow_run:
    workflows:
      - Quality
    types:
      - completed

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  sonar:
    name: SonarQube
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: coverage-report
          path: .
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
